### ISSUE TITLE
Version 6.3 Compatibility

### ISSUE THREAD

**Issue by theparker** [LaSepp/ScreenConnectIntegration#1]
I have been testing your code on ScreenConnect and it works perfectly with Version 6.1 but the code breaks with version 6.3.

Code fails at **InitCategories()** when trying to make POST requests to _Services/PageService.ashx/GetHostSessionInfo_

The server returns with HTTP Error 500 (Internal Server Error)

Is this something you've come across? Is there something I am not doing right?

PS: Thanks for your effort in creating this great work.

**Comment by theparker** [comment]
I fixed it by changing **ctl03** to **ctl05**

```c#
loginString += HttpUtility.UrlEncode("ctl00$Main$ctl03") + "=" + HttpUtility.UrlEncode("Login") + "&";
```

to 

```c#
loginString += HttpUtility.UrlEncode("ctl00$Main$ctl05") + "=" + HttpUtility.UrlEncode("Login") + "&";
```

in **loginSc6**

**Comment by LaSepp** [comment]
Thanks for the patch!
I've updated the source and binary files in the repository with additional detection code, so it should work with both the old and the new SC6 versions.
