### ISSUE TITLE
Latest Stable not working - 20.11.1622.7619 - Getting 403 Forbidden

### ISSUE THREAD

**Issue by willzzzzzzzz** [LaSepp/ScreenConnectIntegration#4]
I am in process of upgrading to latest stable from 6.0. During my testing the app works to list remote machines, but when you attempt to connect or send command, both will return an error message of "The remote server returned an error: (403) Forbidden".

We are using on-prem instance if that makes any difference.

I assumed this was something to do with our upgrade, so I built a clean windows install with latest version and it erred with 403.

Steps to reproduce:
Setup a new instance of 20.11.1622.7619 on a test Windows server.
Run through setup wizard.
Add first Windows machine.
Open ScreenConnectIntegration tray app.
Enter valid creds.
Attempt to connect to an access session on the test Windows machine.

Update: I tested against 20.9 on the same server and your code works as you noted on latest fixed issue, so I do believe something is different in the latest version. 
Update: I tested against 20.10 and your code works.

**Comment by LaSepp** [comment]
Hello willzzzzzzzz,

I will update my local version and try to figure out what is different in the new 20.11. version.

**Comment by LaSepp** [comment]
@willzzzzzzzz 
The X-Anti-Forgery-Token Header seems to be used now in version 20.11.x
I added support to load the current token from the server and send it back when running a command / opening a host session.
Please try if this fixes the issue.

**Comment by willzzzzzzzz** [comment]
@LaSepp you are amazing!!!  It is working again! Thanks for keeping up with this library over the years!
